### ISSUE TITLE
Issue with usb

### ISSUE THREAD

**Issue by banshit122** [sudo-self/samsung-frp#2]
Hey, I've been testing your Python program for bypassing Google's FRP. When I run "main.py," I get the following error:

PS C:\Users\bhvghm\Desktop\samsung-frp-frp> python main.py
Traceback (most recent call last):
  File "C:\Users\bhvghm\Desktop\samsung-frp-frp\main.py", line 12, in <module>
    main()
  File "C:\Users\bhvghm\Desktop\samsung-frp-frp\main.py", line 6, in main
    samsungGalaxyToModemMode()
  File "C:\Users\bhvghm\Desktop\samsung-frp-frp\usbswitcher.py", line 20, in samsungGalaxyToModemMode
    dev = usb.core.find(idVendor=SAMSUNG_GALAXY_ID_VENDOR, idProduct=SAMSUNG_GALAXY_ID_PRODUCT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bhvghm\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by kagbontaen** [comment]
this code was made specifically for samsung devices and would not be able to help

**Comment by kagbontaen** [comment]
> Hey, I've been testing your Python program for bypassing Google's FRP. When I run "main.py," I get the following error:
> 
> PS C:\Users\bhvghm\Desktop\samsung-frp-frp> python main.py
> Traceback (most recent call last):
>   File "C:\Users\bhvghm\Desktop\samsung-frp-frp\main.py", line 12, in <module>
>     main()
>   File "C:\Users\bhvghm\Desktop\samsung-frp-frp\main.py", line 6, in main
>     samsungGalaxyToModemMode()
>   File "C:\Users\bhvghm\Desktop\samsung-frp-frp\usbswitcher.py", line 20, in samsungGalaxyToModemMode
>     dev = usb.core.find(idVendor=SAMSUNG_GALAXY_ID_VENDOR, idProduct=SAMSUNG_GALAXY_ID_PRODUCT)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\bhvghm\AppData\Local\Programs\Python\Python312\Lib\site-packages\usb\core.py", line 1309, in find
>     raise NoBackendError('No backend available')
> usb.core.NoBackendError: No backend available

Use the at_util.py directly
